sudo: required
language: python
services: docker

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy3

install:
  - pip install --use-feature 2020-resolver -U setuptools twine pip sphinx tox tox-travis

script:
  - tox
  - ./bin/check_readme.sh

branches:
  except:
    - standalone

jobs:
  include:
    - python: 3.9
      install: pip install -U black
      script: black --check .
    - python: 3.9
      install: pip install --use-feature 2020-resolver -U pip twine
      script: ./bin/test-docker.sh
